using './main.bicep'

param appId = readEnvironmentVariable('APP_ID', 'template')
param environmentName = readEnvironmentVariable('AZURE_ENV_NAME')
param location = readEnvironmentVariable('AZURE_LOCATION')
param resourceNameSuffix = readEnvironmentVariable('AZURE_RESOURCE_NAME_SUFFIX', '')
param sharedSubscriptionId = readEnvironmentVariable('SHARED_SUBSCRIPTION_ID', readEnvironmentVariable('AZURE_SUBSCRIPTION_ID'))
param sharedResourceGroupName = readEnvironmentVariable('SHARED_RESOURCE_GROUP', 'rg-shared')
param monitoringSubscriptionId = readEnvironmentVariable('MONITORING_SUBSCRIPTION_ID', readEnvironmentVariable('AZURE_SUBSCRIPTION_ID'))
param monitoringResourceGroupName = readEnvironmentVariable('MONITORING_RESOURCE_GROUP', 'rg-dx-monitoring')
param appInsightsName = readEnvironmentVariable('APP_INSIGHTS_NAME', 'appi-dx-core')
param vnetName = readEnvironmentVariable('VNET_NAME')
param integrationSubnetName = readEnvironmentVariable('INTEGRATION_SUBNET_NAME', 'snet-webapps')
param sqlServerName = readEnvironmentVariable('SQL_SERVER_NAME')
param sqlDatabaseName = readEnvironmentVariable('SQL_DATABASE_NAME')
param keyVaultName = readEnvironmentVariable('KEY_VAULT_NAME')
param entraClientId = readEnvironmentVariable('ENTRA_CLIENT_ID')
param entraSecretName = readEnvironmentVariable('ENTRA_SECRET_NAME')
param appServicePlanName = readEnvironmentVariable('APP_SERVICE_PLAN_NAME')
param appServicePlanSku = readEnvironmentVariable('APP_SERVICE_PLAN_SKU', 'B1')
param pythonVersion = readEnvironmentVariable('PYTHON_VERSION', '3.13')
